import type { LucideIcon } from "lucide-react";
import {
  BadgeDollarSign,
  Brain,
  Briefcase,
  ClipboardList,
  Code2,
  FileSearch,
  HeartHandshake,
  LifeBuoy,
  Megaphone,
  Mic,
  ServerCog,
  Sparkles,
  UserSearch,
  Workflow,
} from "lucide-react";

export type AgentTemplate = {
  id: string;
  name: string;
  agentName: string;
  category: "support" | "sales" | "ops" | "engineering" | "marketing" | "people" | "custom";
  icon: LucideIcon;
  tagline: string;
  description: string;
  personaId: string;
  suggestedAppIds: string[];
  suggestedKnowledgeType: "support-docs" | "sales-collateral" | "internal-docs" | "code-repos" | "marketing-assets" | "hr-policies" | null;
  defaultModel?: string;
};

export const AGENT_TEMPLATES: readonly AgentTemplate[] = [
  {
    id: "support",
    name: "Customer support",
    agentName: "Support Agent",
    category: "support",
    icon: LifeBuoy,
    tagline: "Resolve customer questions, deflect tickets, escalate when needed.",
    description: "Calm, clear, empathetic support grounded in your help center and product docs.",
    personaId: "customer-support",
    suggestedAppIds: ["telegram-channel", "slack-channel", "brave-search"],
    suggestedKnowledgeType: "support-docs",
  },
  {
    id: "sales-sdr",
    name: "Sales SDR",
    agentName: "Sales Agent",
    category: "sales",
    icon: BadgeDollarSign,
    tagline: "Qualify leads, send follow-ups, push the pipeline forward.",
    description: "Outreach, qualification, and follow-through that moves deals along without losing your voice.",
    personaId: "sales-representative",
    suggestedAppIds: ["slack-channel", "brave-search"],
    suggestedKnowledgeType: "sales-collateral",
  },
  {
    id: "recruiter",
    name: "Recruiter",
    agentName: "Recruiting Agent",
    category: "people",
    icon: UserSearch,
    tagline: "Source candidates, screen applicants, schedule interviews.",
    description: "A persistent recruiter that drafts outreach, summarizes candidates, and keeps the funnel moving.",
    personaId: "operations-coordinator",
    suggestedAppIds: ["slack-channel", "brave-search"],
    suggestedKnowledgeType: "hr-policies",
  },
  {
    id: "onboarding-buddy",
    name: "Onboarding buddy",
    agentName: "Onboarding Buddy",
    category: "people",
    icon: HeartHandshake,
    tagline: "Help new hires ramp up with answers, links, and friendly nudges.",
    description: "Knows your handbook, tools, and team rituals. Answers the awkward questions new hires don't want to ask.",
    personaId: "executive-assistant",
    suggestedAppIds: ["slack-channel"],
    suggestedKnowledgeType: "hr-policies",
  },
  {
    id: "meeting-notetaker",
    name: "Meeting notetaker",
    agentName: "Notetaker",
    category: "ops",
    icon: Mic,
    tagline: "Summarize meetings, extract decisions, draft follow-ups.",
    description: "Turns long calls into crisp notes, action items, and follow-up drafts you can send.",
    personaId: "operations-coordinator",
    suggestedAppIds: ["slack-channel"],
    suggestedKnowledgeType: "internal-docs",
  },
  {
    id: "code-reviewer",
    name: "Code reviewer",
    agentName: "Code Reviewer",
    category: "engineering",
    icon: Code2,
    tagline: "Review PRs, catch issues, suggest improvements.",
    description: "A pragmatic engineer that explains trade-offs and looks for bugs, regressions, and rough edges.",
    personaId: "software-engineer",
    suggestedAppIds: ["browser", "diffs"],
    suggestedKnowledgeType: "code-repos",
  },
  {
    id: "qa-triage",
    name: "QA triage",
    agentName: "QA Triage",
    category: "engineering",
    icon: ClipboardList,
    tagline: "Triage bugs, reproduce issues, route to the right team.",
    description: "Reads bug reports, finds duplicates, and assigns severity so engineers can focus on fixing.",
    personaId: "software-engineer",
    suggestedAppIds: ["browser"],
    suggestedKnowledgeType: "code-repos",
  },
  {
    id: "marketing-copywriter",
    name: "Marketing copywriter",
    agentName: "Copywriter",
    category: "marketing",
    icon: Megaphone,
    tagline: "Draft posts, emails, ads, and landing copy in your voice.",
    description: "Concrete drafts and messaging that sound like your brand, not generic AI prose.",
    personaId: "marketing-specialist",
    suggestedAppIds: ["brave-search"],
    suggestedKnowledgeType: "marketing-assets",
  },
  {
    id: "data-analyst",
    name: "Data analyst",
    agentName: "Analyst",
    category: "ops",
    icon: FileSearch,
    tagline: "Pull data, build summaries, answer business questions.",
    description: "Structured analysis and clear comparisons. Tells you what the numbers actually mean.",
    personaId: "research-analyst",
    suggestedAppIds: ["brave-search"],
    suggestedKnowledgeType: "internal-docs",
  },
  {
    id: "procurement",
    name: "Procurement",
    agentName: "Procurement Agent",
    category: "ops",
    icon: Briefcase,
    tagline: "Compare vendors, draft RFPs, track approvals.",
    description: "Keeps purchasing organized and surfaces the right trade-offs before you sign.",
    personaId: "operations-coordinator",
    suggestedAppIds: ["slack-channel", "brave-search"],
    suggestedKnowledgeType: "internal-docs",
  },
  {
    id: "it-helpdesk",
    name: "IT helpdesk",
    agentName: "IT Helpdesk",
    category: "support",
    icon: ServerCog,
    tagline: "Reset accounts, walk through fixes, escalate hardware issues.",
    description: "First line of internal IT support. Resolves common issues and routes the rest to humans.",
    personaId: "customer-support",
    suggestedAppIds: ["slack-channel"],
    suggestedKnowledgeType: "internal-docs",
  },
  {
    id: "operations-assistant",
    name: "Ops assistant",
    agentName: "Ops Assistant",
    category: "ops",
    icon: Workflow,
    tagline: "Coordinate work, summarize updates, keep teams in sync.",
    description: "Reliable execution support that turns messy work into clear next steps.",
    personaId: "operations-coordinator",
    suggestedAppIds: ["slack-channel"],
    suggestedKnowledgeType: "internal-docs",
  },
  {
    id: "research-assistant",
    name: "Research assistant",
    agentName: "Research Assistant",
    category: "ops",
    icon: Brain,
    tagline: "Investigate topics, synthesize sources, write briefs.",
    description: "Reads, compares, and summarizes so you walk into meetings already prepared.",
    personaId: "research-analyst",
    suggestedAppIds: ["brave-search", "browser"],
    suggestedKnowledgeType: "internal-docs",
  },
  {
    id: "custom",
    name: "Custom agent",
    agentName: "Custom Agent",
    category: "custom",
    icon: Sparkles,
    tagline: "Start from a blank slate and define the persona yourself.",
    description: "For when none of the templates fit. Full control over name, persona, and tools.",
    personaId: "custom",
    suggestedAppIds: [],
    suggestedKnowledgeType: null,
  },
] as const;

export function getAgentTemplate(id?: string | null): AgentTemplate | null {
  if (!id) return null;
  return AGENT_TEMPLATES.find((entry) => entry.id === id) ?? null;
}
