#!/usr/bin/env -S npx tsx
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import programmeOrientationPack from "../src/lib/training-scripts/programme-orientation";
import pythonForDataPack from "../src/lib/training-scripts/python-for-data";
import type { ModuleScriptPack, SegmentBlock, SlideScript } from "../src/lib/training-scripts/types";

const PACKS: Array<{ pack: ModuleScriptPack; outputPath: string }> = [
  {
    pack: programmeOrientationPack,
    outputPath: resolve(process.cwd(), "programme-orientation/facilitator-guide.md"),
  },
  {
    pack: pythonForDataPack,
    outputPath: resolve(process.cwd(), "python-training/facilitator-guide.md"),
  },
];

function bulletList(items: string[]): string {
  return items.map((item) => `- ${item.trim()}`).join("\n");
}

function renderSegment(segment: SegmentBlock): string {
  const out: string[] = [];
  out.push(`### Slides ${segment.start} to ${segment.end} -- ${segment.label}`);
  out.push("");
  out.push(`**Objective:** ${segment.objective}`);
  out.push("");
  out.push(`**Delivery stance:** ${segment.delivery}`);
  out.push("");
  out.push("**Facilitator moves:**");
  out.push("");
  out.push(bulletList(segment.facilitatorMoves));
  if (segment.debrief && segment.debrief.length > 0) {
    out.push("");
    out.push("**Debrief prompts:**");
    out.push("");
    out.push(bulletList(segment.debrief));
  }
  out.push("");
  return out.join("\n");
}

function renderSlide(slide: SlideScript): string {
  const out: string[] = [];
  out.push(`## Slide ${slide.slideNumber} (${slide.deckId}) -- Day ${slide.day}, ${slide.segment}`);
  out.push("");
  out.push(`**Core message:** ${slide.coreMessage}`);
  out.push("");
  out.push("**Say to the room:**");
  out.push("");
  for (const paragraph of slide.sayThis) {
    out.push(`> ${paragraph.trim()}`);
    out.push(">");
  }
  if (out[out.length - 1] === ">") out.pop();
  if (slide.presenterCues && slide.presenterCues.length > 0) {
    out.push("");
    out.push("**Presenter cues (do not say aloud):**");
    out.push("");
    out.push(bulletList(slide.presenterCues));
  }
  if (slide.showThis) {
    out.push("");
    out.push(`**Show:** ${slide.showThis}`);
  }
  if (slide.askThis && slide.askThis.length > 0) {
    out.push("");
    out.push("**Ask:**");
    out.push("");
    out.push(bulletList(slide.askThis));
  }
  if (slide.doThis && slide.doThis.length > 0) {
    out.push("");
    out.push("**Do:**");
    out.push("");
    out.push(bulletList(slide.doThis));
  }
  if (slide.watchFor && slide.watchFor.length > 0) {
    out.push("");
    out.push("**Watch for:**");
    out.push("");
    out.push(bulletList(slide.watchFor));
  }
  out.push("");
  out.push(`**Land the point:** ${slide.landThePoint}`);
  if (slide.transition) {
    out.push("");
    out.push(`**Transition:** ${slide.transition}`);
  }
  if (typeof slide.estMinutes === "number") {
    out.push("");
    out.push(`_Approx pacing: ${slide.estMinutes} min._`);
  }
  out.push("");
  return out.join("\n");
}

function renderPack(pack: ModuleScriptPack): string {
  const out: string[] = [];
  out.push(`# ${pack.moduleTitle} -- Facilitator Delivery Script`);
  out.push("");
  out.push(
    "> Auto-generated from `src/lib/training-scripts/" +
      `${pack.moduleSlug}.ts\`. Do not edit this file by hand. Update the structured data and re-run \`npm run build:facilitator-guide\`.`,
  );
  out.push("");
  out.push("## Module snapshot");
  out.push("");
  out.push("| Detail | Value |");
  out.push("|--------|-------|");
  out.push(`| Module slug | \`${pack.moduleSlug}\` |`);
  out.push(`| Duration | ${pack.durationDays} days, ${pack.hoursPerDay} hours per day |`);
  out.push(`| Slides | ${pack.totalSlides} |`);
  out.push(`| Segments | ${pack.segments.length} |`);
  out.push("");
  out.push("## How to use this guide");
  out.push("");
  out.push(
    bulletList([
      "Read the **Say to the room** lines as written. They are the literal spoken script for live banking-cohort delivery, in a warm first-person trainer voice. Deliver them; do not paraphrase.",
      "Use the **Presenter cues** section as your private direction track for each slide. They are deliberately not in the spoken script.",
      "Use the **Ask**, **Do**, and **Watch for** sections as the facilitator moves you make around each slide. Do not skip them.",
      "Use the **Land the point** line as the closing beat for every slide. It is intentionally short.",
      "If anything in this guide drifts from the live deck or the workspace artefacts, regenerate this file rather than editing it locally.",
    ]),
  );
  out.push("");
  out.push("---");
  out.push("");
  out.push("## Segment map");
  out.push("");
  for (const segment of pack.segments) {
    out.push(renderSegment(segment));
    out.push("---");
    out.push("");
  }
  out.push("## Slide-by-slide delivery script");
  out.push("");

  let currentDay: number | null = null;
  for (const slide of pack.slides) {
    if (slide.day !== currentDay) {
      currentDay = slide.day;
      out.push(`# Day ${currentDay}`);
      out.push("");
    }
    out.push(renderSlide(slide));
    out.push("---");
    out.push("");
  }
  return out.join("\n");
}

function main() {
  for (const { pack, outputPath } of PACKS) {
    if (pack.slides.length !== pack.totalSlides) {
      console.error(
        `[build-facilitator-guide] ${pack.moduleSlug}: slides.length=${pack.slides.length} does not match totalSlides=${pack.totalSlides}`,
      );
      process.exitCode = 1;
      continue;
    }
    const markdown = renderPack(pack);
    writeFileSync(outputPath, markdown, "utf8");
    console.log(`[build-facilitator-guide] wrote ${outputPath} (${markdown.length} chars)`);
  }
}

main();
